### ISSUE TITLE
Allow players to change health and resolve 

### ISSUE THREAD

**Issue by jwylie01** [fvtt-fria-ligan/blade-runner-foundry-vtt#12]
### Description

Currently users cannot increase their max health or resolve on their player sheet when they add specialities that increase these and it is up to the GM to do that. Would be much easier if the players could make those changes on their own. 

### Suggested solution

Allow players to have full access to the sheet configuration section or at least add an option for the GM to turn on in settings so they can give players access if they want.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Stefouch** [comment]
Related to #6
