### ISSUE TITLE
A way to manage chases

### ISSUE THREAD

**Issue by Raldanash** [fvtt-fria-ligan/blade-runner-foundry-vtt#23]
### Description

It would be good to have a way for players (and the GM) to select their chase maneuvers in the game. 

### Suggested solution

This could be by means of a card deck ...

### Alternative

... or maybe by creating a pop-up prompt / survey style functionality with the six options that the GM can finish and that then posts the choices made by each player / GM to the chat. (a bit like easy poll module)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Stefouch** [comment]
So the new **[Simultaneous Cards](https://foundryvtt.com/packages/simultaneous-cards)** module I developed allows you to do that.

I'm adding the *premium modules* tag to this feature request as a reminder for me to create the maneuver cards in the future.

**Comment by Stefouch** [comment]
A deck of chase maneveurs cards will be added in v1.1.0 of the starter set module.
