### ISSUE TITLE
Cosmetic Issue In Player List When Using Minimal UI

### ISSUE THREAD

**Issue by KoDaMoJo** [fvtt-fria-ligan/blade-runner-foundry-vtt#24]
### Describe the bug

When the Minimal UI module is active, the Player List label and icon are still visible.
![image](https://user-images.githubusercontent.com/125324792/218608736-e46747a4-99dd-4107-97ae-d6500ee3ecbe.png)

TEST: The only test I could do is to activate the same modules in each Free League game on the assumption that they are similar enough in build. Of all the YZ games and Symbaroum, only Blade Runner and Vaesen do not minimize the player list correctly. The assumption, of course, may be false. This is how it appears in Forbidden Lands.
![image](https://user-images.githubusercontent.com/125324792/218610011-5fa6d3cb-4b15-4500-b5bf-3874db39e301.png)

### Reproduction

Install Minimal UI module, and activate the module in Manage Modules. The issue presents in the player list when Settings > Player List Behavior is set to either: Always Visible, Auto-Hide, or Click to Toggle.

### System Info

```sh
OS: Windows 10
Client: Foundry App and Chrome (Forge)
Foundry Version: 10.291
```

### Logs

commons.js:12582 Foundry VTT | Foundry Commons Framework Loaded
foundry.js:79678 _______________________________________________________________
 _____ ___  _   _ _   _ ____  ______   __ __     _______ _____ 
|  ___/ _ \| | | | \ | |  _ \|  _ \ \ / / \ \   / |_   _|_   _|
| |_ | | | | | | |  \| | | | | |_) \ V /   \ \ / /  | |   | |  
|  _|| |_| | |_| | |\  | |_| |  _ < | |     \ V /   | |   | |  
|_|   \___/ \___/|_| \_|____/|_| \_\|_|      \_/    |_|   |_|  
===============================================================
foundry.js:79688 Foundry VTT | Reestablishing existing session 9f396b35eb665bcb5191adf4
foundry.js:7711 Foundry VTT | Connected to server socket using session 9f396b35eb665bcb5191adf4
libWrapper-api.js:802 libWrapper: Version 1.12.12.0 (099aa51) ready.
foundry.js:7807 Foundry VTT | Initializing Foundry Virtual Tabletop Game
colorSetting.js:664 colorsettings | initializing
main.js:22 chat-portrait | Initializing chat-portrait
logger.mjs:24 core-settings-expanded | Initializing CORE-EXPANDED.ABOUT.Title!
lib.js:88 pin-cushion |  init pin-cushion
logger.mjs:24 regions | Initializing Regions
statuscounter.js:17 statuscounter | Initializing statuscounter
yze-combat.js:1 YZEC | Initializing the Year Zero Combat Module
foundry.js:3133 Foundry VTT | Synchronized official game time in 18ms
foundry.js:6887 Foundry VTT | Retrieved and compiled template systems/blade-runner/templates/actor/actor-damage-chatcard.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template systems/blade-runner/templates/actor/actor-sheet-config.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template systems/blade-runner/templates/actor/character/character-limited-sheet.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template systems/blade-runner/templates/actor/character/character-sheet.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template systems/blade-runner/templates/actor/character/inventory-partial.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template systems/blade-runner/templates/actor/character/sheet-tabs/bio-tab.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template systems/blade-runner/templates/actor/character/sheet-tabs/combat-tab.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template systems/blade-runner/templates/actor/character/sheet-tabs/inventory-tab.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template systems/blade-runner/templates/actor/character/sheet-tabs/mods-tab.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template systems/blade-runner/templates/actor/character/sheet-tabs/stats-tab.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template systems/blade-runner/templates/components/dialog/range-picker-dialog.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template systems/blade-runner/templates/components/roll/roll-askdie-dialog.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template systems/blade-runner/templates/components/roll/roll-chatcard-infos-partial.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template systems/blade-runner/templates/components/roll/roll-chatcard-tooltip-partial.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template systems/blade-runner/templates/components/roll/roll-chatcard.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template systems/blade-runner/templates/components/roll/roll-push-select-dialog.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template systems/blade-runner/templates/components/roll/roller.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template systems/blade-runner/templates/item/actions-partial.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template systems/blade-runner/templates/item/attacks-partial.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template systems/blade-runner/templates/item/item-chatcard.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template systems/blade-runner/templates/item/item-sheet.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template systems/blade-runner/templates/item/modifiers-partial.hbs
blade-runner-core-game.js:62 Blade Runner RPG | Core Game module | Ready!
blade-runner-starter-set.js:20 Blade Runner RPG | Core Game module | Ready!
foundry.js:6887 Foundry VTT | Retrieved and compiled template modules/chat-portrait/templates/chat-portrait-form.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template /modules/core-settings-expanded/templates/partials/core.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template /modules/core-settings-expanded/templates/partials/mapnote.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template /modules/core-settings-expanded/templates/partials/scene.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template /modules/core-settings-expanded/templates/partials/journal.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template modules/regions/templates/partials/documents.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template modules/regions/templates/partials/custom-keys.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template modules/yze-combat/templates/chat/draw-initiative-chatcard.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template modules/yze-combat/templates/combat/choose-card-dialog.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template modules/yze-combat/templates/combat/choose-combatant-dialog.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template modules/yze-combat/templates/sidebar/combat-tracker.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template modules/yze-combat/templates/sidebar/combatant-cards-config.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template modules/yze-combat/templates/sidebar/combatant-group-color-picker.hbs
foundry.js:6771 Foundry VTT | Loaded localization file lang/en.json
foundry.js:6771 Foundry VTT | Loaded localization file systems/blade-runner/lang/en.json
foundry.js:6771 Foundry VTT | Loaded localization file modules/chat-images/languages/en.json
foundry.js:6771 Foundry VTT | Loaded localization file modules/chat-portrait/languages/en.json
foundry.js:6771 Foundry VTT | Loaded localization file modules/colorsettings/lang/en.json
foundry.js:6771 Foundry VTT | Loaded localization file modules/core-settings-expanded/languages/en.json
foundry.js:6771 Foundry VTT | Loaded localization file modules/dice-so-nice/lang/en.json
foundry.js:6771 Foundry VTT | Loaded localization file modules/foundryvtt-simple-calendar/lang/en.json
foundry.js:6771 Foundry VTT | Loaded localization file modules/lib-wrapper/lang/en.json
foundry.js:6771 Foundry VTT | Loaded localization file modules/minimal-ui/lang/en.json
foundry.js:6771 Foundry VTT | Loaded localization file modules/pause-icon/lang/en.json
foundry.js:6771 Foundry VTT | Loaded localization file modules/pin-cushion/languages/en.json
foundry.js:6771 Foundry VTT | Loaded localization file modules/popout/lang/en.json
foundry.js:6771 Foundry VTT | Loaded localization file modules/quick-insert/lang/en.json
foundry.js:6771 Foundry VTT | Loaded localization file modules/regions/languages/en.json
foundry.js:6771 Foundry VTT | Loaded localization file modules/simultaneous-cards/lang/en.json
foundry.js:6771 Foundry VTT | Loaded localization file modules/statuscounter/lang/en.json
foundry.js:6771 Foundry VTT | Loaded localization file modules/vtta-tokenizer/lang/en.json
foundry.js:6771 Foundry VTT | Loaded localization file modules/yze-combat/lang/en.json
foundry.js:80869 Foundry VTT | Delaying load of sound modules/adventuremusic/backgrounds/TheStation.mp3 until after first user gesture
foundry.js:5099 Foundry VTT | Rendering SceneNavigation
foundry.js:5099 Foundry VTT | Rendering Notifications
foundry.js:5099 Foundry VTT | Rendering Sidebar
foundry.js:5099 Foundry VTT | Rendering PlayerList
foundry.js:5099 Foundry VTT | Rendering Hotbar
foundry.js:5099 Foundry VTT | Rendering Pause
foundry.js:5099 Foundry VTT | Rendering SceneControls
foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/hud/navigation.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/sidebar/sidebar.html
foundry.js:5099 Foundry VTT | Rendering ActorDirectory
foundry.js:5099 Foundry VTT | Rendering CardsDirectory
foundry.js:5099 Foundry VTT | Rendering ChatLog
foundry.js:5099 Foundry VTT | Rendering _YearZeroCombatTracker
foundry.js:5099 Foundry VTT | Rendering CompendiumDirectory
foundry.js:5099 Foundry VTT | Rendering ItemDirectory
foundry.js:5099 Foundry VTT | Rendering JournalDirectory
foundry.js:5099 Foundry VTT | Rendering PlaylistDirectory
foundry.js:5099 Foundry VTT | Rendering SceneDirectory
foundry.js:5099 Foundry VTT | Rendering Settings
foundry.js:5099 Foundry VTT | Rendering RollTableDirectory
foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/user/players.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/hud/hotbar.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/hud/pause.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/hud/controls.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/sidebar/document-partial.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/sidebar/document-partial.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/sidebar/chat-log.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/sidebar/compendium-directory.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/sidebar/document-partial.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/sidebar/document-partial.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/sidebar/scene-partial.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/sidebar/settings.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/sidebar/document-partial.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/sidebar/playlist-partial.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
6foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/sidebar/document-directory.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/sidebar/playlists-directory.html
foundry.js:63231 Foundry VTT | Fonts loaded and ready.
utils.min.mjs:8 
    PixiJS 6.5.2 - ✰ WebGL 2 ✰      http://www.pixijs.com/    ♥♥♥ 
foundry.js:20900 Foundry VTT | Viewing Scene Electric Dreams Landing Page
foundry.js:23648 Foundry VTT | Drawing game canvas for scene Electric Dreams Landing Page
foundry.js:25946 Foundry VTT | Loaded modules/blade-runner-core-game/assets/illustrations/br_core01_fiery_the%20angels_fell_18-19.webp (2%)
foundry.js:25946 Foundry VTT | Loaded systems/blade-runner/assets/blade-runner-banner-small.webp (4%)
foundry.js:25946 Foundry VTT | Loaded modules/blade-runner-core-game/assets/scenes/br_la_tto2c_start_small.webp (5%)
foundry.js:25946 Foundry VTT | Loaded my-data/misc-images/blade-runner/logo_electric-dreams.webp (7%)
foundry.js:25946 Foundry VTT | Loaded my-data/tiles/chibbin-grove_dashing-dashboards/504178-Empty-Box1-9x4-1.png (9%)
foundry.js:25946 Foundry VTT | Loaded modules/blade-runner-starter-set/assets/actors/fenna-cropped.webp (11%)
foundry.js:25946 Foundry VTT | Loaded modules/blade-runner-starter-set/assets/actors/percival-cropped.webp (13%)
foundry.js:25946 Foundry VTT | Loaded modules/blade-runner-starter-set/assets/actors/bakker-cropped.webp (14%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/combat.svg (16%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/cowled.svg (18%)
foundry.js:25946 Foundry VTT | Loaded modules/blade-runner-starter-set/assets/actors/nowak-cropped.webp (20%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/aura.svg (21%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/padlock.svg (23%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/up.svg (25%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/down.svg (27%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/skull.svg (29%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/light.svg (30%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/light-off.svg (32%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/explosion.svg (34%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/sound.svg (36%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/sound-off.svg (38%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/door-closed-outline.svg (39%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/door-open-outline.svg (41%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/door-secret-outline.svg (43%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/door-locked-outline.svg (45%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/unconscious.svg (46%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/sleep.svg (48%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/daze.svg (50%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/falling.svg (52%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/net.svg (54%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/paralysis.svg (55%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/wing.svg (57%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/blind.svg (59%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/deaf.svg (61%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/silenced.svg (63%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/terror.svg (64%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/fire.svg (66%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/frozen.svg (68%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/lightning.svg (70%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/acid.svg (71%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/blood.svg (73%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/biohazard.svg (75%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/poison.svg (77%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/sun.svg (79%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/regen.svg (80%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/degen.svg (82%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/downgrade.svg (84%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/upgrade.svg (86%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/invisible.svg (88%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/target.svg (89%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/eye.svg (91%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/angel.svg (93%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/fire-shield.svg (95%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/ice-shield.svg (96%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/mage-shield.svg (98%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/holy-shield.svg (100%)
foundry.js:30347 Foundry VTT | Drawing the WeatherEffects canvas layer
foundry.js:30347 Foundry VTT | Drawing the CanvasBackgroundAlterationEffects canvas layer
foundry.js:30347 Foundry VTT | Drawing the CanvasIlluminationEffects canvas layer
foundry.js:30347 Foundry VTT | Drawing the CanvasColorationEffects canvas layer
foundry.js:30347 Foundry VTT | Drawing the CanvasVisibility canvas layer
foundry.js:30347 Foundry VTT | Drawing the GridLayer canvas layer
foundry.js:30347 Foundry VTT | Drawing the DrawingsLayer canvas layer
foundry.js:30347 Foundry VTT | Drawing the TemplateLayer canvas layer
foundry.js:30347 Foundry VTT | Drawing the TilesLayer canvas layer
foundry.js:30347 Foundry VTT | Drawing the WallsLayer canvas layer
foundry.js:30347 Foundry VTT | Drawing the TokenLayer canvas layer
foundry.js:30347 Foundry VTT | Drawing the SoundsLayer canvas layer
foundry.js:30347 Foundry VTT | Drawing the LightingLayer canvas layer
foundry.js:30347 Foundry VTT | Drawing the NotesLayer canvas layer
foundry.js:30347 Foundry VTT | Drawing the ControlsLayer canvas layer
foundry.js:5099 Foundry VTT | Rendering HeadsUpDisplay
init.js:64 Imported  true Version  1.0.1 Migration  1.0.1
quick-insert.ts:86 Quick Insert | Initializing...
quick-insert.ts:120 Quick Insert | Search Application ready
logger.js:51 Tokenizer | INFO > Ready
foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/hud/hud.html
foundry.js:63204 Font family "IdentikalSans, Consolas, sans-Serif" failed to load.
loadFont @ foundry.js:63204
foundry.js:80290 Foundry VTT | Activating pending audio playback with user gesture.

### Priority this issue should have?

Low (formatting issues, things that don't impact operation)

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Blade Runner system).

**Comment by Stefouch** [comment]
I found the source of the issue and will release a patch with the next update.
