### ISSUE TITLE
Roll Tables in Case file generator returning "null"

### ISSUE THREAD

**Issue by Raldanash** [fvtt-fria-ligan/blade-runner-foundry-vtt#33]
### Describe the bug

When rolling from the C ase File Generator, some tables return "null" results. 
Rolls on Table 3, 4, 5

I think these are all roll tables that contain an array with [[choose: 1d6 #...

### Reproduction

recreated new world
imported core module
roll on case file generator table 3, 4, 5

### System Info

```sh
Windows 11 client, foundry running on Debian server (raspberry pi)
FVTT 11.308
Blade Runner 11.0.1
Chrome
```

### Logs

no errors other than font load error 
foundry.js:72898 Font family "Amiri" failed to load.
loadFont @ foundry.js:72898
foundry.js:72898 Font family "Bruno Ace" failed to load.

### Priority this issue should have?

Medium (minor functional impact)

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Blade Runner system).

**Comment by Stefouch** [comment]
Hi @Raldanash !
I unfortunately cannot achieve to reproduce this bug :-(

Does it still occur? If yes, could you share a screenshot?
