### ISSUE TITLE
Only Crushing Criticals are being rolled for players

### ISSUE THREAD

**Issue by Lockbox313** [fvtt-fria-ligan/blade-runner-foundry-vtt#35]
### Describe the bug

For players an attack mode set to Piercing is set to crushing criticals.  For the GM the drop down has both critical tables but is defaulting to to crushing 

### Reproduction

![problem](https://github.com/fvtt-fria-ligan/blade-runner-foundry-vtt/assets/8994813/9cdcfcd8-45e9-4384-be31-dbe9473e7eb5)

### System Info

```sh
Windows 10
Client Foundry Desktop for GM, Chrome for player
Foundry V11.315
```

### Priority this issue should have?

Medium (minor functional impact)

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Blade Runner system).

**Comment by Stefouch** [comment]
Hi @Lockbox313,

Could you try again but with the ID of the table instead of its name. If I remember correctly, the name is case-sensitive. It should have majs and mins, even if it appears all in uppercase in the dialog dropdown.

**Comment by Lockbox313** [comment]
Yes it works with IDs. What are majs and mins

**Comment by Stefouch** [comment]
> What are majs and mins

Sorry, it's my mistake. It's an abbreviation for French *majuscules* (uppercases) et *minuscules* (lowercases).
