### ISSUE TITLE
Implement setting on system level to control the font & size for the handwritten text (gear, talents, combat fields)

### ISSUE THREAD

**Issue by r-valyar** [fvtt-fria-ligan/blade-runner-foundry-vtt#38]
### Description

When using the Blade Runner system, my players and I would to have system setting that overwrites the default handwritten font. This font is very hard to read on any resolution higher than 1080p and for people with bad eye sight. 

### Suggested solution

Implement controls in the system settings to override the handwritten font and size used. I.e. allow to select Arial/Verdana as screen friendly font and size.

### Alternative

Working alternative is CSS code implemented as part of Custom CSS module, provided by the community. 

### Additional context

n/a

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Stefouch** [comment]
Hi @r-valyar ! Thank you for your report.

I'll look into this. You're not the first to comolain with the handwritten font.
