### ISSUE TITLE
Error / placeholder string for character sheet element descriptions (specialities / items)

### ISSUE THREAD

**Issue by Lim-Dul** [fvtt-fria-ligan/blade-runner-foundry-vtt#46]
### Describe the bug

**Actual Result:**
Items dragged onto a character sheet from content module item lists display `[object Promise]` instead of short description.
![image](https://github.com/fvtt-fria-ligan/blade-runner-foundry-vtt/assets/428324/5e734c5c-a877-4953-99c6-62807b4f2e3c)
![image](https://github.com/fvtt-fria-ligan/blade-runner-foundry-vtt/assets/428324/ccf4ab52-18cd-4c37-a104-f2581fcbe15d)

**Expected Result:**
Items dragged onto a character sheet from content module item lists display short description texts.

**Notes:**
* Full text is displayed in the item detail view.
* This seems to be related to a potential API change in Foundry V12 - reports of similar issues in previous Foundry versions state that this could be solved by using async API calls for fetching the relevant values?
* Attempted both disabling _all_ modules as well as keeping only modules that are essential for playing BR enabled (BR content modules) to no avail.

### Reproduction

1. Open a World with the BR ruleset as well as e.g. the `Blade Runner RPG 🦄 - Core Rules` content module
2. Create a player character actor
3. Drag any item and/or specialty from the item list onto the character sheet
4. Observe the inventory and mods tabs on the character sheet

### System Info

```sh
OS: Windows 11 Pro 10.0.22631 Build 22631
Browser: Chrome 26.0.6478.127
Foundry: Version 12 Build 327
Module Version: 12.0.0 (Ruleset) + 3.0.0 Core Rules / Starter Set + 2.0.0 Fiery Angels
```

### Priority this issue should have?

High (a broken feature, major functional impact)

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Blade Runner system).

**Comment by Stefouch** [comment]
Ok I found the issue, and it's indeed caused by Foundry's V12.

This line here:
https://github.com/fvtt-fria-ligan/blade-runner-foundry-vtt/blob/fd43ee83ce28813d42b0bc300227294d513ff045/src/system/handlebars.js#L124

has become asynchronous and returns a "Promise" instead of some text, that's why it is shown "`[object Promise]`"
