### ISSUE TITLE
Dice So Nice / Blade Runner themed custom dice rolls not displaying correctly in DSN versions 5.0.0 - 5.0.4

### ISSUE THREAD

**Issue by Seamonster73** [fvtt-fria-ligan/blade-runner-foundry-vtt#50]
### Describe the bug

Am raising this here for information purposes. A similar issue has already been opened on the DSN git page: https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/issues/438

With the following versions installed:
__________________________________
Foundry Virtual Tabletop: **Version 12 Stable, 12.330**

Game System: **blade-runner, 12.0.1**

dice-so-nice | **5.0.4** | "Dice So Nice!"
__________________________________
The custom dice do not display correctly. The dice textures are garbled or missing. This can be seen by rolling the dice, or by opening the DSN 3D Dice Settings:

![image](https://github.com/user-attachments/assets/d70ae3e6-2e69-413a-88c7-db44c80c557f)

The issue seems to affect all versions of DSN >= v5
DSN version 4.6.10 works correctly.

### Reproduction

Install versions as mentioned above. Roll dice, or open the DSN 3D Dice Settings:

![image](https://github.com/user-attachments/assets/d70ae3e6-2e69-413a-88c7-db44c80c557f)

### System Info

```sh
Foundry Virtual Tabletop: Version 12 Stable, 12.330
Game System: blade-runner, 12.0.1
Active Modules: 21
Performance Mode: 2

OS: macOS 14.5.0 arm (64-bit)
Client: Not)A;Brand/99.0.0.0
GPU: ANGLE (Apple, Apple M2 Pro, OpenGL 4.1)
```

### Priority this issue should have?

Medium (minor functional impact)

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Blade Runner system).

**Comment by DrOgres** [comment]
Fixed by Dice so Nice 5.0.5
